### ISSUE TITLE
Restrict rest API access to specified hostnames

### ISSUE THREAD

**Issue by jframe** [PegaSysEng/eth2signer#102]
Add a host allow list that will restrict access to the rest API to the specified hostnames. This should follow the same approach as the --metrics-host-allowlist but for the rest API and default to allow access to localhost and 127.0.0.1

**Comment by bgravenorst** [comment]
See:
- https://docs.eth2signer.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#http-host-allowlist
- https://docs.eth2signer.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#metrics-host-allowlist
