### ISSUE TITLE
FC list keys API

### ISSUE THREAD

**Issue by jframe** [PegaSysEng/eth2signer#137]
Add support for FC WalletHas RPC which lists all the addresses in the wallet.

The API details are defined here https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L164

There are no arguments.

Example request:
{ "jsonrpc": "2.0", "method": "Filecoin.WalletList", "params": [], "id": 3 }

response:
{
    "jsonrpc": "2.0",
    "result": [
        "t1656rklyebnscuzs5dee3zwh2xknlqsy7r2ypxei",
        "t1krh62mo2fjdc3lqcec3plkgezl2c56ugfan3wiy",
        "t3r7yx4mof636e3xbdlj2ah2l24nebxpgpg2szxueczpxkn2ue2fgkly3z3su7st5firchbrtamwhmrcghvgeq",
        "t3shbmi4rogflrjcflhoinrnhgxe4przqcdv2erbhulein4lbqjslisg7q6s4axsenwf4k4x4fxsk3jewkz5nq"
    ],
    "id": 3
}

- [x] Update signers to return ECPoint instead of string for available identifier
- [x] Implement Filecoin Address spec
- [x] Use FC address as key identifier
- [x] FC list keys for Secp256k1
- [ ] Filecoin BLS Java FFI binding
- [x] FC list keys for BLS

**Comment by MadelineMurray** [comment]
PR linked in doc epic: https://github.com/PegaSysEng/doc.eth2signer/issues/20
