### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by rain-on** [PegaSysEng/eth2signer#22]
Add openAPI support to Eth2Signer so that users can discover what APIs are available, provide documentation and allow for experimentation with the APIs.

This should include
* Exposing the openAPI spec
* Providing swagger ui as part of the application so the documentation can be viewed and API tried out

**Comment by jframe** [comment]
Official vertx openapi integration doesn't allow use of annotations so we would have to create open api spec up front. This is not how we are using openapi in other projects. Elsewhere we are using annotations on the API handlers/controllers to generate the openapi spec.

To take the standard approach we taking elsewhere is going to more effort than the original estimate of 1 point.

**Comment by jframe** [comment]
On further investigation using the design first approach might work well for us. The Vertx openAPI design first approach does not involve code generation afterall.

**Comment by NicolasMassart** [comment]
With this system is there any risk that the openapi spec and the code get out of sync? For instance if a change is made in the code that doesn't work like the spec, will you have an automatic test detecting it?
Also making sure spec is openapi V3 is important.

**Comment by jframe** [comment]
We are using openapi V3.

Planning to use vertx [openapi module](https://vertx.io/docs/vertx-web-api-contract/java/) which ensures that the request stays in sync with the openAPI spec as request is no longer defined in code. There is possibility that the response could get out of sync as the response as this isn't validated by the module as far I know. We will have think of some validation approach here or perhaps go with another solution for implementing openAPI.

**Comment by usmansaleem** [comment]
Part 1, serving static openapi spec. https://github.com/PegaSysEng/eth2signer/pull/91

**Comment by NicolasMassart** [comment]
vertx openapi module seems nice, I guess it requires a lot of refactoring to have it implemented but there's no much methods in the API for the moment.
At least we will be able to add content in spec without annotation issues, examples and comments will add a lot to the doc.

**Comment by usmansaleem** [comment]
Use ReDocly instead of swagger-ui to serve Eth2Signer OpenApi spec

https://github.com/PegaSysEng/eth2signer/pull/93

**Comment by usmansaleem** [comment]
Part 2 (Publish OpenAPI to GitHub Pages), https://github.com/PegaSysEng/eth2signer/pull/95

**Comment by usmansaleem** [comment]
Part 3, Acceptance tests via OpenApi spec. https://github.com/PegaSysEng/eth2signer/pull/98

**Comment by usmansaleem** [comment]
Fixed by https://github.com/PegaSysEng/eth2signer/pull/100

Eth2Signer now uses OpenAPI specific router which validates the API calls as per the spec.
