### ISSUE TITLE
Cache validator keys

### ISSUE THREAD

**Issue by jframe** [PegaSysEng/eth2signer#33]
Cache validator keys so that the keys do not need to be fetched and decrypted each time a key is used to sign a block or attestation.

**Acceptance Criteria**
* Load validator keys referenced by config directory on startup
* Return validator key / artifact signer from Cache if it exists
* If key doesn't exist attempt to load it using the config directory
* Update the cache periodically when config is changed in the config directory. This could be a later feature.

**Comment by rain-on** [comment]
Initial thoughts and layouts here:

https://docs.google.com/document/d/1Ixd7cLvE4WePwcznW25hIJbOD6f7CVbnbdAcXT8QfM0/edit?
ts=5e8127b3#
