### ISSUE TITLE
Allow key config files to have any unique identifier

### ISSUE THREAD

**Issue by jframe** [PegaSysEng/eth2signer#74]
Allow the key config files to have a name other than the public key or address. This will allow key config files to be consistent for secp256k1 keys which use the address and bls12-381 keys which are named using the public keys.

- Allow any unique identifier for the key files
- At startup, need to load private-keys and associated identifier
- For Eth1 keys, these private-keys need to be mapped to public-key → address
- Do we want to cache the identifier → File mapping? Or re-parse on every restart

**Comment by rain-on** [comment]
Currently the Multi-toml loader in the Signers repo assumes the file's name MUST be the ethereum address assoicated with the  private key stored in the referenced key (performed as a check when file loaded). However, this is only valid for Eth1.

1. Remove The filename <--> Key map check in MultiTOmlLoader
2. EthSigner mus maintain mapping between Eth Address <--> Filename (probably need to document that new keys cannot be added to Ethsigner after startup)
3. Ethsigner will also need to ensure that once a file is loaded that it hasn't changed (and thus the mapping is still true after load)

Its worth ensuring the mapping is maintained somewhere generic in EthSigner.
